all: null malloc malloc100 malloc100free freefunny

clean:
		rm -f null

null: null.c
	gcc -g -o null null.c  -Wall


malloc: malloc.c
		gcc -g -o malloc malloc.c -Wall

malloc100: malloc100.c
		gcc -g -o malloc100 malloc100.c -Wall

malloc100free: malloc100free.c
		gcc -g -o malloc100free malloc100free.c -Wall

freefunny: freefunny.c
		gcc -g -o freefunny freefunny.c -Wall